"""Voice-over with Kokoro (offline TTS): script.json -> vo/<id>.wav, cues.json, cues.js

    python3 scripts/vo.py [--models DIR]

Same cue format as physics-videos/toolkit/scripts/vo.mjs. Model files (kokoro-v1.0.onnx,
voices-v1.0.bin) come from github.com/thewh1teagle/kokoro-onnx releases.
"""
import json, os, sys
import numpy as np, soundfile as sf
from kokoro_onnx import Kokoro

here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
models = sys.argv[sys.argv.index('--models') + 1] if '--models' in sys.argv else os.environ.get('KOKORO_DIR', '.')
script = json.load(open(os.path.join(here, 'script.json')))
voice, speed = script.get('voice', 'af_heart'), script.get('speed', 1.0)
lead, tail = script.get('lead', 0.6), script.get('tail', 3.0)
k = Kokoro(os.path.join(models, 'kokoro-v1.0.onnx'), os.path.join(models, 'voices-v1.0.bin'))
os.makedirs(os.path.join(here, 'vo'), exist_ok=True)

lines, order, prev_end = {}, [], 0.0
for i, l in enumerate(script['lines']):
    audio, sr = k.create(l['text'], voice=voice, speed=l.get('speed', speed), lang='en-us')
    # trim leading/trailing near-silence so cue times line up with the first syllable
    idx = np.where(np.abs(audio) > 0.01)[0]
    audio = audio[max(0, idx[0] - int(0.03 * sr)): idx[-1] + int(0.08 * sr)]
    sf.write(os.path.join(here, 'vo', f"{l['id']}.wav"), audio, sr)
    dur = len(audio) / sr
    at = lead if i == 0 else prev_end + l.get('pauseBefore', 0.6)
    lines[l['id']] = {'at': round(at, 2), 'dur': round(dur, 2), 'end': round(at + dur, 2), 'text': l['text']}
    order.append(l['id']); prev_end = at + dur
    print(f"{l['id']:<10} {at:6.2f} -> {at + dur:6.2f}  {l['text'][:60]}")
cues = {'voice': voice, 'total': round(prev_end + tail, 2), 'order': order, 'lines': lines}
json.dump(cues, open(os.path.join(here, 'cues.json'), 'w'), indent=1)
open(os.path.join(here, 'cues.js'), 'w').write('/* generated by scripts/vo.py, do not edit */\nwindow.CUES = ' + json.dumps(cues, indent=1) + ';\n')
print('total', cues['total'])
