/* generated by scripts/vo.py, do not edit */
window.CUES = {
 "voice": "af_heart",
 "total": 70.04,
 "order": [
  "hook",
  "fountain",
  "straight",
  "copycats",
  "brief",
  "root",
  "pod",
  "fix",
  "later",
  "plastic",
  "payoff"
 ],
 "lines": {
  "hook": {
   "at": 0.6,
   "dur": 4.64,
   "end": 5.24,
   "text": "Close your eyes, and you could still pick this bottle out of a crowd. That was the whole point."
  },
  "fountain": {
   "at": 5.94,
   "dur": 6.5,
   "end": 12.44,
   "text": "Coca-Cola started in eighteen eighty-six as a soda fountain drink. Five cents a glass. No bottle at all."
  },
  "straight": {
   "at": 12.94,
   "dur": 4.66,
   "end": 17.6,
   "text": "When bottlers took over, it shipped in plain, straight-sided glass with a paper label."
  },
  "copycats": {
   "at": 18.0,
   "dur": 6.44,
   "end": 24.44,
   "text": "Those labels slid off in tubs of ice water, and copycats like Koka-Nola used the exact same bottles."
  },
  "brief": {
   "at": 25.14,
   "dur": 7.01,
   "end": 32.15,
   "text": "So in nineteen fifteen, the company asked for a bottle you could recognize by feel in the dark, or even broken on the ground."
  },
  "root": {
   "at": 32.75,
   "dur": 5.63,
   "end": 38.38,
   "text": "At the Root Glass Company in Indiana, Earl Dean looked up coca and kola in an encyclopedia."
  },
  "pod": {
   "at": 38.78,
   "dur": 7.04,
   "end": 45.83,
   "text": "He found a cocoa pod instead. Wrong plant. Perfect shape. Its long ribs and round belly became the contour bottle."
  },
  "fix": {
   "at": 46.33,
   "dur": 5.87,
   "end": 52.2,
   "text": "The first version wobbled on the conveyor belt, so they slimmed it down. People called it the hobble skirt."
  },
  "later": {
   "at": 52.8,
   "dur": 6.16,
   "end": 58.96,
   "text": "Painted labels arrived in nineteen fifty-seven. In nineteen sixty, the shape itself was trademarked."
  },
  "plastic": {
   "at": 59.26,
   "dur": 2.11,
   "end": 61.37,
   "text": "Even the plastic bottles kept the curves."
  },
  "payoff": {
   "at": 62.07,
   "dur": 5.37,
   "end": 67.44,
   "text": "So that shape isn't decoration. It's a hundred-year-old anti-copycat device you can feel."
  }
 }
};
