// Voice-over: synthesize every line of script.json, measure it, and lay out a cue sheet.
//
//   node scripts/vo.mjs <videoDir> [--force]
//
// script.json:
// {
//   "voice": "en-US-AndrewMultilingualNeural",   // optional (see VOICES below)
//   "rate": "-3%",                                // optional speaking rate
//   "lead": 0.8,                                  // silence before the first line (s)
//   "tail": 2.5,                                  // hold after the last line (s)
//   "lines": [
//     { "id": "intro", "text": "…" },
//     { "id": "setup", "text": "…", "pauseBefore": 1.2 },   // extra breathing room / time for a visual beat
//     { "id": "reveal", "text": "…", "at": 21.0 }           // or pin a start time (never earlier than the previous line end)
//   ]
// }
//
// Writes: vo/<id>.mp3, cues.json, cues.js  (window.CUES = { total, lines: { id: { at, dur, end, text } } })
// Only lines whose text/voice/rate changed are re-synthesized.
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { EdgeTTS } from 'node-edge-tts';
import { args, probeDuration, readJson, videoDir } from './common.mjs';

export const VOICES = {
  'en-US-AndrewMultilingualNeural': 'warm, confident male (default)',
  'en-US-AvaMultilingualNeural': 'bright, friendly female',
  'en-US-EmmaMultilingualNeural': 'clear, cheerful female',
  'en-US-BrianMultilingualNeural': 'relaxed, conversational male',
  'en-GB-RyanNeural': 'British male, documentary feel',
  'en-GB-SoniaNeural': 'British female, documentary feel',
};

const a = args();
const dir = videoDir(a._[0]);
const script = readJson(join(dir, 'script.json'));
const voice = script.voice || 'en-US-AndrewMultilingualNeural';
const rate = script.rate || '-3%';
const lead = script.lead ?? 0.8, tail = script.tail ?? 2.5;
if (!Array.isArray(script.lines) || !script.lines.length) throw new Error('script.json needs a non-empty "lines" array');
const ids = new Set();
for (const l of script.lines) {
  if (!/^[a-z0-9_-]+$/i.test(l.id || '')) throw new Error(`Bad line id "${l.id}" (use letters, digits, _ or -)`);
  if (ids.has(l.id)) throw new Error(`Duplicate line id "${l.id}"`);
  ids.add(l.id);
  if (!l.text || !l.text.trim()) throw new Error(`Line "${l.id}" has no text`);
}

mkdirSync(join(dir, 'vo'), { recursive: true });
const manPath = join(dir, 'vo', 'manifest.json');
const manifest = readJson(manPath, {});
for (const l of script.lines) {
  const f = join(dir, 'vo', `${l.id}.mp3`);
  const sig = createHash('sha1').update(`${voice}|${rate}|${l.text}`).digest('hex');
  if (!a.force && manifest[l.id] === sig && existsSync(f)) continue;
  let lastErr;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const tts = new EdgeTTS({ voice, rate, outputFormat: 'audio-24khz-96kbitrate-mono-mp3', timeout: 60000 });
      await tts.ttsPromise(l.text, f);
      lastErr = null; break;
    } catch (e) { lastErr = e; await new Promise(r => setTimeout(r, 1500 * attempt)); }
  }
  if (lastErr) throw new Error(`TTS failed for "${l.id}": ${lastErr.message || lastErr}`);
  manifest[l.id] = sig;
  console.log(`synthesized ${l.id}`);
}
writeFileSync(manPath, JSON.stringify(manifest, null, 1));

// lay out cues
const lines = {}; let t = lead, prevEnd = 0;
script.lines.forEach((l, i) => {
  const dur = probeDuration(join(dir, 'vo', `${l.id}.mp3`));
  let at = i === 0 ? lead : prevEnd + (l.pauseBefore ?? 0.6);
  if (typeof l.at === 'number') at = Math.max(l.at, prevEnd + 0.2);
  at = +at.toFixed(2);
  const end = +(at + dur).toFixed(2);
  lines[l.id] = { at, dur: +dur.toFixed(2), end, text: l.text };
  prevEnd = end; t = end;
});
const total = +(t + tail).toFixed(2);
const cues = { voice, rate, total, order: script.lines.map(l => l.id), lines };
writeFileSync(join(dir, 'cues.json'), JSON.stringify(cues, null, 1));
writeFileSync(join(dir, 'cues.js'), `/* generated by scripts/vo.mjs — do not edit */\nwindow.CUES = ${JSON.stringify(cues, null, 1)};\n`);

console.log(`\nCue sheet (${voice}, rate ${rate}) — total ${total}s`);
for (const id of cues.order) { const c = lines[id]; console.log(`  ${id.padEnd(14)} ${c.at.toFixed(2).padStart(6)} → ${c.end.toFixed(2).padStart(6)}  (${c.dur.toFixed(1)}s)  ${c.text.slice(0, 60)}${c.text.length > 60 ? '…' : ''}`); }
